import mongoose from "mongoose";
import dotenv from "dotenv";
import connectDB from "./config/db.js";
import Destination from "./models/Destination.js";
import Package from "./models/Package.js";

dotenv.config();
connectDB();

const destinations = [
  // ─── INDIA ───────────────────────────────────────────────────────────────
  {
    name: "Munnar",
    country: "India", state: "Kerala",
    image: "/images/destinations/Munnar.jpg",
    images: ["/images/destinations/Munnar.jpg"],
    rating: 4.8, reviewCount: 2140, price: 650, duration: "4 Days", category: "Mountain",
    description: "Rolling emerald tea plantations and misty hills in the Western Ghats of Kerala. Munnar is famous for its endless carpets of tea gardens, cool climate, and panoramic viewpoints.",
    shortDescription: "Rolling tea gardens and misty hill views",
    bestTimeToVisit: "September to May",
    topAttractions: ["Tea Museum", "Eravikulam National Park", "Mattupetty Dam", "Top Station Viewpoint"],
    activities: ["Tea plantation trekking", "Boating at Mattupetty", "Spice plantation tour", "Wildlife spotting"],
    foodRecommendations: ["Kerala Sadya", "Appam with stew", "Karimeen fish fry", "Fresh cardamom tea"],
    travelTips: ["Carry a light jacket, evenings get cool", "Book tea factory visits in advance", "Best photography light is early morning"],
    estimatedDailyBudget: 2500,
    coordinates: { lat: 10.0889, lng: 77.0595 },
  },
  {
  name: "Goa Beaches",
  country: "India", state: "Goa",
  image: "/images/destinations/Goa Beaches.jpg",
  images: [
    "/images/destinations/Goa Beaches.jpg",
  ],
  rating: 4.6, reviewCount: 3820, price: 800, duration: "4 Days", category: "Beach",
  description: "Golden beaches, vibrant nightlife, and Portuguese-era churches on India's west coast. Goa blends laid-back beach culture with rich colonial history.",
  shortDescription: "Golden sands and vibrant coastal nightlife",
  bestTimeToVisit: "November to February",
  topAttractions: ["Basilica of Bom Jesus", "Fort Aguada", "Calangute Beach", "Anjuna Flea Market"],
  activities: ["Water sports", "Sunset cruise", "Beach shacks & nightlife", "Spice plantation visit"],
  foodRecommendations: ["Goan fish curry", "Bebinca", "Prawn balchão", "Feni cocktails"],
  travelTips: ["North Goa for nightlife, South Goa for quiet beaches", "Rent a scooter for easy travel", "Book beach shacks ahead in peak season"],
  estimatedDailyBudget: 3000,
  coordinates: { lat: 15.2993, lng: 74.1240 },
},
  {
    name: "Ladakh",
    country: "India", state: "Jammu and Kashmir",
    image: "/images/destinations/Ladakh.jpg",
    images: ["/images/destinations/Ladakh.jpg"],
    rating: 4.9, reviewCount: 1980, price: 1300, duration: "6 Days", category: "Adventure",
    description: "High-altitude desert landscapes, ancient monasteries, and epic mountain passes. Ladakh offers some of the most dramatic scenery in the Himalayas.",
    shortDescription: "High-altitude deserts and Himalayan monasteries",
    bestTimeToVisit: "May to September",
    topAttractions: ["Pangong Lake", "Nubra Valley", "Magnetic Hill", "Thiksey Monastery"],
    activities: ["Bike expeditions", "River rafting on Zanskar", "Camping under stars", "Monastery visits"],
    foodRecommendations: ["Thukpa", "Momos", "Butter tea", "Skyu"],
    travelTips: ["Acclimatize for 1-2 days before high-altitude travel", "Carry cash, ATMs are limited", "Permits required for some border areas"],
    estimatedDailyBudget: 3500,
    coordinates: { lat: 34.1526, lng: 77.5771 },
  },
  {
  name: "Taj Mahal, Agra",
  country: "India", state: "Uttar Pradesh",
  image: "/images/destinations/Taj Mahal, Agra.jpg",
  images: [
    "/images/destinations/Taj Mahal, Agra.jpg",
  ],
  rating: 5.0, reviewCount: 5210, price: 600, duration: "2 Days", category: "Historical",
  description: "The iconic marble mausoleum and UNESCO World Heritage Site, a timeless symbol of eternal love and Mughal architecture at its finest.",
  shortDescription: "The eternal monument of love",
  bestTimeToVisit: "October to March",
  topAttractions: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh"],
  activities: ["Sunrise Taj viewing", "Heritage walk", "Marble inlay workshop visit", "Local bazaar shopping"],
  foodRecommendations: ["Petha (sweet)", "Mughlai biryani", "Bedai and jalebi breakfast"],
  travelTips: ["Visit at sunrise to avoid crowds and heat", "Taj Mahal closed on Fridays", "Carry your own water bottle"],
  estimatedDailyBudget: 1800,
  coordinates: { lat: 27.1751, lng: 78.0421 },
},
  {
    name: "Varanasi",
    country: "India", state: "Uttar Pradesh",
    image: "/images/destinations/Varanasi.jpg",
    images: ["/images/destinations/Varanasi.jpg"],
    rating: 4.7, reviewCount: 2670, price: 500, duration: "3 Days", category: "Spiritual",
    description: "India's spiritual capital, famous for the Ganga Aarti ceremony and ancient temples lining the sacred ghats along the Ganges river.",
    shortDescription: "India's spiritual heart on the Ganges",
    bestTimeToVisit: "October to March",
    topAttractions: ["Kashi Vishwanath Temple", "Dashashwamedh Ghat", "Sarnath", "Assi Ghat"],
    activities: ["Sunrise boat ride", "Ganga Aarti ceremony", "Old city heritage walk", "Silk weaving workshop visit"],
    foodRecommendations: ["Banarasi paan", "Kachori sabzi", "Lassi from Blue Lassi shop"],
    travelTips: ["Book a boat before sunrise for the best ghat views", "Dress modestly near temples", "Bargain at local markets"],
    estimatedDailyBudget: 1600,
    coordinates: { lat: 25.3176, lng: 82.9739 },
  },
  {
    name: "Coorg",
    country: "India", state: "Karnataka",
    image: "/images/destinations/Coorg.jpg",
    images: ["/images/destinations/Coorg.jpg"],
    rating: 4.7, reviewCount: 1540, price: 600, duration: "3 Days", category: "Nature",
    description: "The Scotland of India — coffee plantations, misty hills, and cascading waterfalls.",
    shortDescription: "Coffee plantations and misty hills",
    bestTimeToVisit: "October to March",
    topAttractions: ["Abbey Falls", "Raja's Seat", "Namdroling Monastery", "Dubare Elephant Camp"],
    activities: ["Coffee plantation walk", "River rafting", "Trekking to Tadiandamol", "Elephant interaction"],
    foodRecommendations: ["Pandi curry (pork)", "Kadambuttu", "Filter coffee from local estates"],
    travelTips: ["Roads are winding, avoid night driving", "Carry insect repellent for plantation walks", "Best monsoon greenery July-September"],
    estimatedDailyBudget: 2200,
    coordinates: { lat: 12.3375, lng: 75.8069 },
  },
{
  name: "Jaipur",
  country: "India", state: "Rajasthan",
  image: "/images/destinations/Jaipur.jpg",
  images: [
    "/images/destinations/Jaipur.jpg",
  ],
  rating: 4.8, reviewCount: 3100, price: 700, duration: "4 Days", category: "Historical",
  description: "The Pink City — royal palaces, majestic forts, and vibrant bazaars showcasing the grandeur of Rajasthani heritage.",
  shortDescription: "Royal palaces and vibrant bazaars",
  bestTimeToVisit: "October to March",
  topAttractions: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar"],
  activities: ["Elephant ride at Amber Fort", "Bazaar shopping", "Puppet show", "Heritage hotel dining"],
  foodRecommendations: ["Dal baati churma", "Ghewar", "Laal maas", "Pyaaz kachori"],
  travelTips: ["Bargain firmly in local markets", "Visit forts early to beat the heat", "Carry cash for smaller shops"],
  estimatedDailyBudget: 2400,
  coordinates: { lat: 26.9124, lng: 75.7873 },
},
  {
    name: "Rishikesh",
    country: "India", state: "Uttarakhand",
    image: "/images/destinations/Rishikesh.jpg",
    images: ["/images/destinations/Rishikesh.jpg"],
    rating: 4.7, reviewCount: 2210, price: 450, duration: "4 Days", category: "Adventure",
    description: "The Yoga Capital of the World, nestled in the Himalayan foothills along the sacred Ganges, blending spirituality with adrenaline.",
    shortDescription: "Yoga capital with Himalayan adventure",
    bestTimeToVisit: "September to April",
    topAttractions: ["Laxman Jhula", "Ram Jhula", "Beatles Ashram", "Neelkanth Mahadev Temple"],
    activities: ["White water rafting", "Bungee jumping", "Yoga & meditation retreats", "Camping by the Ganges"],
    foodRecommendations: ["Sattvic thali", "Ganga chai", "German bakery treats"],
    travelTips: ["Alcohol and meat are restricted in most of the town", "Rafting season is best March-June & Sept-Nov", "Book ashram stays early"],
    estimatedDailyBudget: 1800,
    coordinates: { lat: 30.0869, lng: 78.2676 },
  },
  {
    name: "Andaman Islands",
    country: "India", state: "Andaman and Nicobar",
    image: "/images/destinations/Andaman Islands.jpg",
    images: ["/images/destinations/Andaman Islands.jpg"],
    rating: 4.8, reviewCount: 1670, price: 1100, duration: "5 Days", category: "Beach",
    description: "Pristine white-sand beaches, vibrant coral reefs, and crystal-clear turquoise waters in the Bay of Bengal.",
    shortDescription: "Pristine beaches and coral reefs",
    bestTimeToVisit: "October to May",
    topAttractions: ["Radhanagar Beach", "Cellular Jail", "Ross Island", "Havelock Island"],
    activities: ["Scuba diving", "Snorkeling", "Glass-bottom boat ride", "Sea walking"],
    foodRecommendations: ["Fresh seafood platters", "Coconut prawn curry", "Tuna steaks"],
    travelTips: ["Book inter-island ferries in advance", "Diving certification available on-site", "Carry reef-safe sunscreen"],
    estimatedDailyBudget: 3200,
    coordinates: { lat: 11.7401, lng: 92.6586 },
  },
  {
    name: "Hampi",
    country: "India", state: "Karnataka",
    image: "/images/destinations/Hampi.jpg",
    images: ["/images/destinations/Hampi.jpg"],
    rating: 4.6, reviewCount: 1320, price: 400, duration: "3 Days", category: "Historical",
    description: "A UNESCO World Heritage ruin city of ancient temples and boulder-strewn landscapes, once the capital of the Vijayanagara Empire.",
    shortDescription: "Ancient ruins amid boulder landscapes",
    bestTimeToVisit: "October to February",
    topAttractions: ["Virupaksha Temple", "Vittala Temple", "Hampi Bazaar", "Matanga Hill"],
    activities: ["Boulder trekking", "Coracle ride on Tungabhadra", "Cycling through ruins", "Sunset at Hemakuta Hill"],
    foodRecommendations: ["Banana chips (local specialty)", "South Indian thali", "Fresh sugarcane juice"],
    travelTips: ["Rent a bicycle to explore ruins", "Very hot midday — plan visits for morning/evening", "Carry a good camera, sunsets are stunning"],
    estimatedDailyBudget: 1500,
    coordinates: { lat: 15.3350, lng: 76.4600 },
  },
  {
    name: "Kerala Backwaters, Alappuzha",
    country: "India", state: "Kerala",
    image: "/images/destinations/Kerala.jpg",
    images: ["/images/destinations/Kerala.jpg"],
    rating: 4.7, reviewCount: 1980, price: 900, duration: "3 Days", category: "Nature",
    description: "Serene backwaters, tranquil houseboats, and lush palm-lined canals — the heart of God's Own Country.",
    shortDescription: "Tranquil houseboats through palm-lined canals",
    bestTimeToVisit: "November to February",
    topAttractions: ["Vembanad Lake", "Alappuzha Beach", "Kerala Backwater Museum"],
    activities: ["Houseboat stay", "Village canoe tour", "Ayurvedic spa", "Snake boat race (seasonal)"],
    foodRecommendations: ["Karimeen pollichathu", "Coconut rice", "Kerala-style prawn curry"],
    travelTips: ["Book houseboats a few days ahead in peak season", "Mosquito repellent recommended", "Sunset views best from the upper deck"],
    estimatedDailyBudget: 2800,
    coordinates: { lat: 9.4981, lng: 76.3388 },
  },
  {
  name: "Wonderla, Bangalore",
  country: "India", state: "Karnataka",
  image: "/images/destinations/Wonderla, Bangalore.jpg",
  images: [
    "/images/destinations/Wonderla, Bangalore.jpg",
  ],
  rating: 4.5, reviewCount: 4210, price: 250, duration: "1 Day", category: "Adventure",
  description: "One of India's top amusement parks, packed with thrilling rides, water slides, and a resort stay — a perfect family day out.",
  shortDescription: "Thrill rides and water slides for the family",
  bestTimeToVisit: "Year-round, avoid peak summer afternoons",
  topAttractions: ["Recoil roller coaster", "Wave pool", "Cliff Hanger", "3D theatre"],
  activities: ["Water rides", "Land rides", "Kids play zone", "Resort stay"],
  foodRecommendations: ["Park food court variety", "South Indian snacks"],
  travelTips: ["Carry a change of clothes for water rides", "Weekdays are less crowded", "Lockers available for belongings"],
  estimatedDailyBudget: 1500,
  coordinates: { lat: 12.8395, lng: 77.4066 },
},
  {
  name: "Golden Temple, Amritsar",
  country: "India", state: "Punjab",
  image: "/images/destinations/Golden Temple.jpg",
  images: [
    "/images/destinations/Golden Temple.jpg",
  ],
  rating: 4.9, reviewCount: 4100, price: 400, duration: "2 Days", category: "Spiritual",
  description: "The holiest Sikh shrine — a stunning gold-plated gurdwara surrounded by the sacred Amrit Sarovar pool, open to all faiths.",
  shortDescription: "The holiest Sikh shrine in gold",
  bestTimeToVisit: "October to March",
  topAttractions: ["Golden Temple", "Jallianwala Bagh", "Wagah Border Ceremony", "Partition Museum"],
  activities: ["Langar (community meal)", "Early morning prayer", "Wagah border parade", "Heritage walk"],
  foodRecommendations: ["Amritsari kulcha", "Dal makhani", "Lassi", "Pinni"],
  travelTips: ["Cover your head inside the temple", "Remove shoes before entering", "Visit at night for stunning illuminated reflections"],
  estimatedDailyBudget: 1500,
  coordinates: { lat: 31.6200, lng: 74.8765 },
},
  {
    name: "Tirupati Balaji",
    country: "India", state: "Andhra Pradesh",
    image: "/images/destinations/Tirupati Balaji.jpg",
    images: ["/images/destinations/Tirupati Balaji.jpg"],
    rating: 4.8, reviewCount: 5800, price: 350, duration: "2 Days", category: "Spiritual",
    description: "One of the world's most visited pilgrimage sites, home to Lord Venkateswara Temple atop the seven hills of Tirumala.",
    shortDescription: "World's most visited pilgrimage site",
    bestTimeToVisit: "September to February",
    topAttractions: ["Venkateswara Temple", "Akasaganga Teertham", "Silathoranam", "Chandragiri Fort"],
    activities: ["Temple darshan", "Hill trekking", "Prasadam collection", "Kalyana Katta hair offering"],
    foodRecommendations: ["Tirupati laddu (prasadam)", "Pulihora", "Dosa at local restaurants"],
    travelTips: ["Book darshan tickets online well in advance", "Free darshan queues can take 12+ hours", "Special entry tickets recommended for first-timers"],
    estimatedDailyBudget: 1200,
    coordinates: { lat: 13.6288, lng: 79.4192 },
  },
  {
  name: "Meenakshi Temple, Madurai",
  country: "India", state: "Tamil Nadu",
  image: "/images/destinations/Meenakshi Temple.jpg",
  images: [
    "/images/destinations/Meenakshi Temple.jpg",
  ],
  rating: 4.8, reviewCount: 3200, price: 300, duration: "2 Days", category: "Spiritual",
  description: "A breathtaking Dravidian temple famous for its towering gopurams adorned with thousands of intricately carved colorful sculptures.",
  shortDescription: "Towering Dravidian gopurams and sacred tanks",
  bestTimeToVisit: "October to March",
  topAttractions: ["Meenakshi Amman Temple", "Thirumalai Nayakkar Palace", "Gandhi Memorial Museum", "Vandiyur Mariamman Teppakulam"],
  activities: ["Temple tour", "Cultural evening show", "Local silk shopping", "Food street walk"],
  foodRecommendations: ["Madurai kari dosa", "Jigarthanda", "Mutton biryani", "Idiyappam"],
  travelTips: ["Camera not allowed inside the sanctum", "Evening aarti is spectacular", "Hire a local guide for temple history"],
  estimatedDailyBudget: 1200,
  coordinates: { lat: 9.9195, lng: 78.1193 },
},
  {
    name: "Kedarnath Temple",
    country: "India", state: "Uttarakhand",
    image: "/images/destinations/Kedarnath Temple.jpg",
    images: ["/images/destinations/Kedarnath Temple.jpg"],
    rating: 4.9, reviewCount: 2900, price: 900, duration: "4 Days", category: "Spiritual",
    description: "A sacred Himalayan shrine to Lord Shiva, set amid breathtaking snow-capped peaks — one of the Char Dham pilgrimage sites.",
    shortDescription: "Sacred Himalayan shrine in the snow",
    bestTimeToVisit: "May to June, September to October",
    topAttractions: ["Kedarnath Temple", "Vasuki Tal", "Shankaracharya Samadhi", "Chorabari Lake"],
    activities: ["Trek to temple", "Helicopter ride", "Camping", "Photography of Himalayan peaks"],
    foodRecommendations: ["Simple dal rice at dhabas", "Rajma chawal", "Hot chai"],
    travelTips: ["Temple open only May to November", "Carry warm clothes even in summer", "Book helicopter in advance for elderly pilgrims"],
    estimatedDailyBudget: 2500,
    coordinates: { lat: 30.7352, lng: 79.0669 },
  },
  {
  name: "Vaishno Devi",
  country: "India", state: "Jammu and Kashmir",
  image: "/images/destinations/Vaishno Devi.jpg",
  images: [
    "/images/destinations/Vaishno Devi.jpg",
  ],
  rating: 4.8, reviewCount: 3400, price: 500, duration: "2 Days", category: "Spiritual",
  description: "One of India's holiest shrines, perched in the Trikuta Hills — millions of pilgrims trek 14 km through scenic mountain trails each year.",
  shortDescription: "Holy shrine in the Trikuta Hills",
  bestTimeToVisit: "March to October",
  topAttractions: ["Vaishno Devi Cave Shrine", "Bhairon Temple", "Ardh Kuwari", "Sanjichhat"],
  activities: ["14 km trek", "Helicopter ride", "Pony ride", "Night trek"],
  foodRecommendations: ["Langar prasad", "Rajma rice", "Khichdi"],
  travelTips: ["Register at Katra base camp before starting trek", "Comfortable shoes essential", "Battery torches recommended for night trek"],
  estimatedDailyBudget: 1800,
  coordinates: { lat: 33.0294, lng: 74.9520 },
},
  {
    name: "Somnath Temple",
    country: "India", state: "Gujarat",
    image: "/images/destinations/Somnath Temple.jpg",
    images: ["/images/destinations/Somnath Temple.jpg"],
    rating: 4.7, reviewCount: 2100, price: 350, duration: "2 Days", category: "Spiritual",
    description: "One of the twelve Jyotirlinga shrines of Lord Shiva, standing majestically by the Arabian Sea — rebuilt seven times through history.",
    shortDescription: "Ancient Jyotirlinga by the Arabian Sea",
    bestTimeToVisit: "October to March",
    topAttractions: ["Somnath Temple", "Triveni Sangam", "Somnath Museum", "Bhalka Tirth"],
    activities: ["Evening light show", "Temple darshan", "Sunset at beach", "Heritage walk"],
    foodRecommendations: ["Gujarati thali", "Dhokla", "Fafda-jalebi", "Undhiyu"],
    travelTips: ["Sound and light show in the evening is spectacular", "Photography allowed outside temple only", "Combine with Dwarka visit for full Gujarat pilgrimage"],
    estimatedDailyBudget: 1200,
    coordinates: { lat: 20.8880, lng: 70.4012 },
  },
  {
    name: "Mysore Palace",
    country: "India", state: "Karnataka",
    image: "/images/destinations/Mysore Palace.jpg",
    images: ["/images/destinations/Mysore Palace.jpg"],
    rating: 4.7, reviewCount: 2800, price: 400, duration: "2 Days", category: "Historical",
    description: "A dazzling Indo-Saracenic palace illuminated by 97,000 light bulbs on weekends — one of India's most visited monuments.",
    shortDescription: "Illuminated royal palace of Karnataka",
    bestTimeToVisit: "October to February",
    topAttractions: ["Mysore Palace", "Chamundeshwari Temple", "Brindavan Gardens", "Mysore Zoo"],
    activities: ["Palace light show", "Dasara festival (seasonal)", "Silk shopping", "Zoo visit"],
    foodRecommendations: ["Mysore pak", "Bisi bele bath", "Mysore masala dosa", "Chiroti"],
    travelTips: ["Palace is lit every Sunday and public holidays", "Dasara festival in Oct is spectacular", "Hire audio guide inside the palace"],
    estimatedDailyBudget: 1500,
    coordinates: { lat: 12.3052, lng: 76.6552 },
  },
  {
  name: "Shirdi Sai Baba Temple",
  country: "India", state: "Maharashtra",
  image: "/images/destinations/Shirdi Sai Baba Temple.jpg",
  images: [
    "/images/destinations/Shirdi Sai Baba Temple.jpg",
  ],
  rating: 4.7, reviewCount: 4200, price: 350, duration: "2 Days", category: "Spiritual",
  description: "A revered pilgrimage site dedicated to Sai Baba, drawing millions of devotees from all religions who seek blessings and peace.",
  shortDescription: "Beloved pilgrimage site for all faiths",
  bestTimeToVisit: "October to March",
  topAttractions: ["Sai Baba Samadhi Mandir", "Dwarkamai Mosque", "Gurusthan", "Chavadi"],
  activities: ["Kakad aarti (early morning)", "Noon aarti", "Shrine visit", "Prasadam collection"],
  foodRecommendations: ["Prasad at the temple", "Simple Maharashtrian thali"],
  travelTips: ["Book accommodation in advance, especially on weekends", "Online booking for aarti slots available", "Queue management system — follow instructions"],
  estimatedDailyBudget: 1200,
  coordinates: { lat: 19.7657, lng: 74.4775 },
},
  {
    name: "Konark Sun Temple",
    country: "India", state: "Odisha",
    image: "/images/destinations/Konark Sun Temple.jpg",
    images: ["/images/destinations/Konark Sun Temple.jpg"],
    rating: 4.7, reviewCount: 1600, price: 300, duration: "2 Days", category: "Historical",
    description: "A 13th-century UNESCO World Heritage Site shaped like a colossal stone chariot dedicated to the Sun God — a pinnacle of Kalinga architecture.",
    shortDescription: "13th-century stone chariot UNESCO site",
    bestTimeToVisit: "October to February",
    topAttractions: ["Konark Sun Temple", "Konark Beach", "Archaeological Museum", "Chandrabhaga Beach"],
    activities: ["Temple exploration", "Konark Dance Festival (seasonal)", "Beach visit", "Puri day trip"],
    foodRecommendations: ["Pakhala bhata", "Dalma", "Chhena poda (cheese dessert)", "Machha jhola"],
    travelTips: ["Combine with Puri and Bhubaneswar for the Golden Triangle", "Best light for photography is early morning", "Carry water, very hot in summer"],
    estimatedDailyBudget: 1200,
    coordinates: { lat: 19.8876, lng: 86.0946 },
  },
  {
    name: "Jim Corbett National Park",
    country: "India", state: "Uttarakhand",
    image: "/images/destinations/Jim Corbett National Park.jpg",
    images: ["/images/destinations/Jim Corbett National Park.jpg"],
    rating: 4.6, reviewCount: 1800, price: 550, duration: "3 Days", category: "Nature",
    description: "India's oldest and most celebrated national park, famous for Bengal tiger safaris and diverse wildlife in dense sal forests.",
    shortDescription: "India's oldest tiger reserve",
    bestTimeToVisit: "November to June",
    topAttractions: ["Dhikala Zone", "Bijrani Zone", "Jhirna Zone", "Corbett Museum"],
    activities: ["Jeep safari", "Elephant safari", "Bird watching", "Nature walk"],
    foodRecommendations: ["Forest rest house meals", "Local Kumaoni cuisine", "Bhatt ki churkani"],
    travelTips: ["Book safari permits online well in advance", "Dhikala zone has highest tiger sighting probability", "Best sightings are at dawn and dusk"],
    estimatedDailyBudget: 2500,
    coordinates: { lat: 29.5300, lng: 78.7747 },
  },
  {
    name: "Nandi Hills, Bangalore",
    country: "India", state: "Karnataka",
    image: "/images/destinations/Nandi Hills, Bangalore.jpg",
    images: ["/images/destinations/Nandi Hills, Bangalore.jpg"],
    rating: 4.4, reviewCount: 2900, price: 150, duration: "1 Day", category: "Nature",
    description: "A popular sunrise trekking spot near Bangalore, offering stunning hilltop views, cool weather, and ancient temples at 1,478 metres.",
    shortDescription: "Sunrise trekking spot near Bangalore",
    bestTimeToVisit: "September to February",
    topAttractions: ["Sunrise viewpoint", "Bhoga Nandeeshwara Temple", "Tipu Sultan's Summer Residence", "Amruth Sarovar Lake"],
    activities: ["Sunrise trekking", "Cycling", "Paragliding", "Temple visit"],
    foodRecommendations: ["Local breakfast stalls at the base", "Hot idli-vada", "Masala chai"],
    travelTips: ["Start by 4 AM to catch sunrise", "Gate opens at 6 AM, arrive early", "Very crowded on weekends"],
    estimatedDailyBudget: 800,
    coordinates: { lat: 13.3702, lng: 77.6835 },
  },
  {
    name: "Innovative Film City, Bangalore",
    country: "India", state: "Karnataka",
    image: "/images/destinations/Innovative Film City, Bangalore.jpg",
    images: ["/images/destinations/Innovative Film City, Bangalore.jpg"],
    rating: 4.2, reviewCount: 1800, price: 300, duration: "1 Day", category: "Adventure",
    description: "A Bollywood-themed entertainment park near Bangalore with film sets, rides, cultural shows, and a wax museum — great for families.",
    shortDescription: "Bollywood sets and family entertainment",
    bestTimeToVisit: "Year-round",
    topAttractions: ["Film sets replica zone", "Wax museum", "Haunted house", "Mini golf"],
    activities: ["Set walk-through", "Cultural shows", "Rides", "Photography"],
    foodRecommendations: ["Food court variety", "Chaat stalls"],
    travelTips: ["Combo tickets offer better value", "Best for families with children", "Weekdays are less crowded"],
    estimatedDailyBudget: 1200,
    coordinates: { lat: 12.9698, lng: 77.5099 },
  },

  // ─── INTERNATIONAL ────────────────────────────────────────────────────────
  {
  name: "Bali",
  country: "Indonesia",
  image: "/images/destinations/Bali.jpg",
  images: [
    "/images/destinations/Bali.jpg",
  ],
  rating: 4.8, reviewCount: 4750, price: 1200, duration: "5 Days", category: "Beach",
  description: "Beautiful tropical paradise with lush rice terraces, ancient temples, and pristine beaches across the Island of the Gods.",
  shortDescription: "Tropical paradise of temples and rice terraces",
  bestTimeToVisit: "April to October",
  topAttractions: ["Tanah Lot Temple", "Tegallalang Rice Terraces", "Uluwatu Temple", "Ubud Monkey Forest"],
  activities: ["Surfing", "Temple hopping", "Rice terrace trekking", "Balinese cooking class"],
  foodRecommendations: ["Nasi goreng", "Babi guling", "Fresh coconut", "Sate lilit"],
  travelTips: ["Rent a scooter for flexibility", "Dress modestly at temples", "Negotiate prices at local markets"],
  estimatedDailyBudget: 4500,
  coordinates: { lat: -8.3405, lng: 115.0920 },
},
  {
  name: "Maldives",
  country: "Maldives",
  image: "/images/destinations/Maldives.jpg",
  images: [
    "/images/destinations/Maldives.jpg",
  ],
  rating: 4.9, reviewCount: 3960, price: 2400, duration: "5 Days", category: "Beach",
  description: "Overwater villas and turquoise lagoons in a tropical dream — one of the world's most iconic luxury island getaways.",
  shortDescription: "Overwater villas and turquoise lagoons",
  bestTimeToVisit: "November to April",
  topAttractions: ["Male City", "Banana Reef", "Maafushi Island", "Vaadhoo Bioluminescent Beach"],
  activities: ["Snorkeling", "Sunset dolphin cruise", "Overwater spa", "Deep-sea fishing"],
  foodRecommendations: ["Garudhiya fish soup", "Mas huni", "Fresh tropical seafood"],
  travelTips: ["Resorts are on private islands, plan transfers ahead", "Alcohol restricted outside resort islands", "Pack reef-safe sunscreen"],
  estimatedDailyBudget: 9000,
  coordinates: { lat: 3.2028, lng: 73.2207 },
},
  {
  name: "Dubai",
  country: "UAE",
  image: "/images/destinations/Dubai.jpg",
  images: [
    "/images/destinations/Dubai.jpg",
  ],
  rating: 4.7, reviewCount: 5100, price: 1800, duration: "4 Days", category: "Luxury",
  description: "A futuristic skyline, thrilling desert safaris, and world-class shopping define this ultra-modern desert metropolis.",
  shortDescription: "Futuristic skyline and desert adventures",
  bestTimeToVisit: "November to March",
  topAttractions: ["Burj Khalifa", "Dubai Mall", "Palm Jumeirah", "Dubai Marina"],
  activities: ["Desert safari with dune bashing", "Burj Khalifa observation deck", "Dhow cruise dinner", "Luxury shopping"],
  foodRecommendations: ["Shawarma", "Al Machboos", "Emirati coffee with dates"],
  travelTips: ["Summer heat is extreme, prefer winter travel", "Dress modestly in public areas", "Metro is efficient for getting around"],
  estimatedDailyBudget: 6000,
  coordinates: { lat: 25.2048, lng: 55.2708 },
},
  {
  name: "Paris",
  country: "France",
  image: "/images/destinations/Paris.jpg",
  images: [
    "/images/destinations/Paris.jpg",
  ],
  rating: 4.9, reviewCount: 6210, price: 2100, duration: "6 Days", category: "Historical",
  description: "The city of lights, romance, and iconic landmarks — Paris blends art, history, and culinary excellence like nowhere else.",
  shortDescription: "The city of lights and timeless romance",
  bestTimeToVisit: "April to June, September to October",
  topAttractions: ["Eiffel Tower", "Louvre Museum", "Notre-Dame", "Montmartre"],
  activities: ["Seine river cruise", "Museum hopping", "Café culture walk", "Versailles day trip"],
  foodRecommendations: ["Croissants", "Coq au vin", "French macarons", "Wine and cheese pairing"],
  travelTips: ["Book museum tickets online to skip lines", "Metro is the fastest way around", "Learn a few basic French phrases"],
  estimatedDailyBudget: 7000,
  coordinates: { lat: 48.8566, lng: 2.3522 },
},
  {
  name: "Switzerland",
  country: "Switzerland",
  image: "/images/destinations/Switzerland.jpg",
  images: [
    "/images/destinations/Switzerland.jpg",
  ],
  rating: 4.9, reviewCount: 3450, price: 2600, duration: "7 Days", category: "Mountain",
  description: "Snow-capped Alps, crystal lakes, and postcard-perfect villages come together in one of Europe's most breathtaking countries.",
  shortDescription: "Alpine peaks and postcard-perfect villages",
  bestTimeToVisit: "June to September, December to March",
  topAttractions: ["Matterhorn", "Jungfraujoch", "Lake Lucerne", "Interlaken"],
  activities: ["Alpine train rides", "Skiing", "Lake cruises", "Paragliding"],
  foodRecommendations: ["Swiss fondue", "Rösti", "Swiss chocolate", "Raclette"],
  travelTips: ["Swiss Travel Pass covers most transport", "Book alpine train seats in advance", "Weather changes fast, layer up"],
  estimatedDailyBudget: 8500,
  coordinates: { lat: 46.8182, lng: 8.2275 },
},
  {
    name: "Kyoto",
    country: "Japan",
    image: "/images/destinations/Kyoto.jpg",
    images: ["/images/destinations/Kyoto.jpg"],
    rating: 4.8, reviewCount: 2870, price: 1900, duration: "6 Days", category: "Historical",
    description: "Ancient temples, cherry blossoms, and timeless Japanese culture converge in this former imperial capital.",
    shortDescription: "Ancient temples and cherry blossom charm",
    bestTimeToVisit: "March to May, October to November",
    topAttractions: ["Fushimi Inari Shrine", "Kinkaku-ji Golden Pavilion", "Arashiyama Bamboo Grove", "Gion District"],
    activities: ["Tea ceremony", "Kimono walk", "Temple hopping", "Bamboo grove trek"],
    foodRecommendations: ["Kaiseki dining", "Matcha desserts", "Yudofu (tofu hotpot)"],
    travelTips: ["Cherry blossom season is very crowded, book early", "IC card for easy transit", "Respect quiet zones near temples"],
    estimatedDailyBudget: 6500,
    coordinates: { lat: 35.0116, lng: 135.7681 },
  },
  {
  name: "Santorini",
  country: "Greece",
  image: "/images/destinations/Santorini.jpg",
  images: [
    "/images/destinations/Santorini.jpg",
  ],
  rating: 4.9, reviewCount: 4120, price: 2000, duration: "5 Days", category: "Beach",
  description: "Whitewashed cliffside villages overlooking the deep blue Aegean Sea — one of the most photographed destinations on Earth.",
  shortDescription: "Whitewashed cliffs over the Aegean Sea",
  bestTimeToVisit: "April to June, September to October",
  topAttractions: ["Oia Village", "Fira Town", "Red Beach", "Akrotiri Ruins"],
  activities: ["Sunset watching in Oia", "Wine tasting tour", "Catamaran cruise", "Volcanic hot springs swim"],
  foodRecommendations: ["Greek salad with local tomatoes", "Fava purée", "Moussaka", "Santorini wine"],
  travelTips: ["Book Oia sunset spot early, it gets crowded", "ATVs are a fun way to explore", "Wear comfortable shoes for cliffside walks"],
  estimatedDailyBudget: 7500,
  coordinates: { lat: 36.3932, lng: 25.4615 },
},
  {
  name: "New York City",
  country: "USA",
  image: "/images/destinations/New York City.jpg",
  images: [
    "/images/destinations/New York City.jpg",
  ],
  rating: 4.7, reviewCount: 7200, price: 2200, duration: "5 Days", category: "Adventure",
  description: "The city that never sleeps — skyscrapers, world-class museums, Broadway shows, and diverse food from every corner of the globe.",
  shortDescription: "The city that never sleeps",
  bestTimeToVisit: "April to June, September to November",
  topAttractions: ["Statue of Liberty", "Central Park", "Times Square", "Brooklyn Bridge"],
  activities: ["Broadway show", "Museum of Modern Art", "High Line walk", "Food tour"],
  foodRecommendations: ["NY-style pizza", "Bagels with lox", "Pastrami sandwich", "Cheesecake"],
  travelTips: ["Get a MetroCard for subway travel", "Book Broadway tickets in advance", "Walk the High Line for free skyline views"],
  estimatedDailyBudget: 8000,
  coordinates: { lat: 40.7128, lng: -74.0060 },
},
  {
  name: "Rome",
  country: "Italy",
  image: "/images/destinations/Rome.jpg",
  images: [
    "/images/destinations/Rome.jpg",
  ],
  rating: 4.8, reviewCount: 5600, price: 1700, duration: "5 Days", category: "Historical",
  description: "The Eternal City — ancient ruins, world-class Vatican art, Renaissance fountains, and unforgettable Italian cuisine at every corner.",
  shortDescription: "Eternal city of ruins and Renaissance art",
  bestTimeToVisit: "April to June, September to October",
  topAttractions: ["Colosseum", "Vatican Museums", "Trevi Fountain", "Pantheon"],
  activities: ["Colosseum guided tour", "Vatican & Sistine Chapel", "Pasta-making class", "Vespa tour"],
  foodRecommendations: ["Cacio e pepe", "Supplì", "Gelato", "Tiramisu"],
  travelTips: ["Book Colosseum tickets online", "Romans eat dinner late (8-9 PM)", "Wear covered shoulders at Vatican"],
  estimatedDailyBudget: 6000,
  coordinates: { lat: 41.9028, lng: 12.4964 },
},
  {
  name: "Tokyo",
  country: "Japan",
  image: "/images/destinations/Tokyo.jpg",
  images: [
    "/images/destinations/Tokyo.jpg",
  ],
  rating: 4.9, reviewCount: 5800, price: 2000, duration: "6 Days", category: "Adventure",
  description: "An electrifying metropolis where ultramodern technology meets ancient tradition — neon-lit streets, sushi bars, and serene temples.",
  shortDescription: "Ultramodern meets ancient Japan",
  bestTimeToVisit: "March to May, September to November",
  topAttractions: ["Shibuya Crossing", "Senso-ji Temple", "Shinjuku", "teamLab Borderless"],
  activities: ["Sushi breakfast at Tsukiji", "Robot Restaurant", "Day trip to Mt. Fuji", "Anime shopping in Akihabara"],
  foodRecommendations: ["Ramen", "Sushi omakase", "Tonkatsu", "Matcha soft serve"],
  travelTips: ["Get a Suica/Pasmo card for transit", "7-Eleven and convenience stores are amazing", "Book teamLab in advance"],
  estimatedDailyBudget: 7000,
  coordinates: { lat: 35.6762, lng: 139.6503 },
},
  {
  name: "London",
  country: "United Kingdom",
  image: "/images/destinations/London.jpg",
  images: [
    "/images/destinations/London.jpg",
  ],
  rating: 4.8, reviewCount: 6100, price: 2300, duration: "6 Days", category: "Historical",
  description: "A world capital of culture, history, and diversity — from royal palaces and world-class museums to vibrant street markets and live music.",
  shortDescription: "Royal history meets modern culture",
  bestTimeToVisit: "June to August, September to October",
  topAttractions: ["Big Ben & Houses of Parliament", "Tower of London", "British Museum", "Buckingham Palace"],
  activities: ["Thames river cruise", "West End theatre", "Borough Market food tour", "Day trip to Stonehenge"],
  foodRecommendations: ["Fish and chips", "Full English breakfast", "Afternoon tea", "Chicken tikka masala"],
  travelTips: ["Oyster card for the Tube", "Many world-class museums are free", "Book theatre tickets in advance"],
  estimatedDailyBudget: 8000,
  coordinates: { lat: 51.5074, lng: -0.1278 },
},
  {
  name: "Barcelona",
  country: "Spain",
  image: "/images/destinations/Barcelona.jpg",
  images: [
    "/images/destinations/Barcelona.jpg",
  ],
  rating: 4.8, reviewCount: 4900, price: 1600, duration: "5 Days", category: "Historical",
  description: "Gaudí's surreal architecture, sun-drenched beaches, and a legendary food scene make Barcelona one of Europe's most exciting cities.",
  shortDescription: "Gaudí architecture and Mediterranean beaches",
  bestTimeToVisit: "May to June, September to October",
  topAttractions: ["Sagrada Família", "Park Güell", "La Rambla", "Camp Nou"],
  activities: ["Gaudí architecture tour", "Tapas bar hopping", "Beach day at Barceloneta", "Flamenco show"],
  foodRecommendations: ["Pan con tomate", "Patatas bravas", "Paella", "Crema catalana"],
  travelTips: ["Book Sagrada Família well in advance", "Pickpockets are common on La Rambla", "Dinner starts at 9-10 PM"],
  estimatedDailyBudget: 5500,
  coordinates: { lat: 41.3851, lng: 2.1734 },
},
  {
  name: "Singapore",
  country: "Singapore",
  image: "/images/destinations/Singapore.jpg",
  images: [
    "/images/destinations/Singapore.jpg",
  ],
  rating: 4.8, reviewCount: 4300, price: 1500, duration: "4 Days", category: "Luxury",
  description: "A dazzling city-state where futuristic architecture, diverse cultures, and legendary street food come together seamlessly.",
  shortDescription: "Futuristic city of diversity and food",
  bestTimeToVisit: "February to April",
  topAttractions: ["Gardens by the Bay", "Marina Bay Sands", "Sentosa Island", "Chinatown"],
  activities: ["Universal Studios", "Night safari", "Hawker centre food tour", "Cable car to Sentosa"],
  foodRecommendations: ["Chilli crab", "Hainanese chicken rice", "Char kway teow", "Kaya toast"],
  travelTips: ["MRT is excellent and cheap", "Hawker centres are best value for food", "Chewing gum is banned"],
  estimatedDailyBudget: 6000,
  coordinates: { lat: 1.3521, lng: 103.8198 },
},
  {
  name: "Amsterdam",
  country: "Netherlands",
  image: "/images/destinations/Amsterdam.jpg",
  images: [
    "/images/destinations/Amsterdam.jpg",
  ],
  rating: 4.7, reviewCount: 3800, price: 1800, duration: "4 Days", category: "Historical",
  description: "Charming canal rings, world-class art museums, and a cycling culture that makes Amsterdam one of Europe's most liveable and loveable cities.",
  shortDescription: "Canals, cycling and world-class art",
  bestTimeToVisit: "April to May, September to October",
  topAttractions: ["Rijksmuseum", "Anne Frank House", "Van Gogh Museum", "Canal Ring"],
  activities: ["Canal boat tour", "Bicycle tour", "Tulip field visit (seasonal)", "Heineken Experience"],
  foodRecommendations: ["Stroopwafels", "Bitterballen", "Raw herring", "Dutch pancakes"],
  travelTips: ["Book Anne Frank House tickets months ahead", "Rent a bike — it's the best way to explore", "Watch out for tram tracks when cycling"],
  estimatedDailyBudget: 6500,
  coordinates: { lat: 52.3676, lng: 4.9041 },
},
  {
  name: "Istanbul",
  country: "Turkey",
  image: "/images/destinations/Istanbul.jpg",
  images: [
    "/images/destinations/Istanbul.jpg",
  ],
  rating: 4.8, reviewCount: 4500, price: 1100, duration: "5 Days", category: "Historical",
  description: "Where East meets West — Istanbul straddles two continents with Ottoman palaces, Byzantine basilicas, and one of the world's great bazaars.",
  shortDescription: "Where East meets West across two continents",
  bestTimeToVisit: "April to June, September to November",
  topAttractions: ["Hagia Sophia", "Topkapi Palace", "Grand Bazaar", "Blue Mosque"],
  activities: ["Bosphorus cruise", "Turkish bath (hammam)", "Spice Bazaar visit", "Whirling dervish show"],
  foodRecommendations: ["Kebabs", "Baklava", "Turkish breakfast spread", "Simit with tea"],
  travelTips: ["Haggle at the Grand Bazaar", "Carry lira — not all places take cards", "Shoes off in mosques"],
  estimatedDailyBudget: 4000,
  coordinates: { lat: 41.0082, lng: 28.9784 },
},
  {
    name: "New Zealand",
    country: "New Zealand",
    image: "/images/destinations/New Zealand.jpg",
    images: ["/images/destinations/New Zealand.jpg"],
    rating: 4.9, reviewCount: 2900, price: 2500, duration: "8 Days", category: "Adventure",
    description: "Dramatic fjords, volcanic peaks, Māori culture, and endless adventure activities across the North and South Islands.",
    shortDescription: "Fjords, volcanoes and Māori culture",
    bestTimeToVisit: "December to February",
    topAttractions: ["Milford Sound", "Hobbiton", "Rotorua Geothermal Park", "Queenstown"],
    activities: ["Bungee jumping", "Skydiving", "Glacier hiking", "Lord of the Rings tour"],
    foodRecommendations: ["Hāngi feast", "Green-lipped mussels", "Lamb rack", "Pavlova"],
    travelTips: ["Rent a campervan for flexibility", "Book Milford Sound cruises in advance", "Weather changes fast in the South Island"],
    estimatedDailyBudget: 8000,
    coordinates: { lat: -40.9006, lng: 174.8860 },
  },
  {
  name: "Machu Picchu",
  country: "Peru",
  image: "/images/destinations/Machu Picchu.jpg",
  images: [
    "/images/destinations/Machu Picchu.jpg",
  ],
  rating: 4.9, reviewCount: 3100, price: 1800, duration: "5 Days", category: "Adventure",
  description: "The Lost City of the Incas — a breathtaking 15th-century citadel perched high in the Andes, one of the world's greatest archaeological sites.",
  shortDescription: "The legendary Lost City of the Incas",
  bestTimeToVisit: "May to September",
  topAttractions: ["Machu Picchu Citadel", "Sun Gate", "Huayna Picchu", "Aguas Calientes"],
  activities: ["Inca Trail trek", "Sunrise at the citadel", "Llama spotting", "Zip-lining"],
  foodRecommendations: ["Ceviche", "Lomo saltado", "Quinoa soup", "Chicha morada"],
  travelTips: ["Book Inca Trail permits months in advance", "Acclimatize in Cusco first", "Entry tickets strictly timed — book online"],
  estimatedDailyBudget: 5500,
  coordinates: { lat: -13.1631, lng: -72.5450 },
},
  {
    name: "Safari, Kenya",
    country: "Kenya",
    image: "/images/destinations/Safari, Kenya.jpg",
    images: ["/images/destinations/Safari, Kenya.jpg"],
    rating: 4.9, reviewCount: 2200, price: 3000, duration: "7 Days", category: "Adventure",
    description: "Witness the spectacular Great Migration across the Masai Mara and encounter the Big Five in their natural savanna habitat.",
    shortDescription: "Big Five safaris and the Great Migration",
    bestTimeToVisit: "July to October",
    topAttractions: ["Masai Mara", "Amboseli National Park", "Lake Nakuru", "Nairobi National Park"],
    activities: ["Jeep game drives", "Hot air balloon safari", "Masai village visit", "Bird watching"],
    foodRecommendations: ["Nyama choma (grilled meat)", "Ugali", "Sukuma wiki", "Kenyan chai"],
    travelTips: ["Book camps well in advance for migration season", "Neutral-coloured clothing for safaris", "Malaria prophylaxis recommended"],
    estimatedDailyBudget: 10000,
    coordinates: { lat: -1.2921, lng: 36.8219 },
  },
  {
    name: "Amazon Rainforest",
    country: "Brazil",
    image: "/images/destinations/Amazon Rainforest.jpg",
    images: ["/images/destinations/Amazon Rainforest.jpg"],
    rating: 4.5, reviewCount: 1400, price: 1500, duration: "6 Days", category: "Nature",
    description: "Immersive jungle expeditions through the world's largest rainforest — home to unparalleled biodiversity and indigenous cultures.",
    shortDescription: "Immersive expeditions in the world's largest rainforest",
    bestTimeToVisit: "June to November",
    topAttractions: ["Amazon River cruise", "Anavilhanas Archipelago", "Meeting of the Waters", "Indigenous village visit"],
    activities: ["Jungle trekking", "Night safari", "Piranha fishing", "Pink river dolphin spotting"],
    foodRecommendations: ["Tacacá (soup)", "Pato no tucupi", "Açaí bowl", "Grilled river fish"],
    travelTips: ["Book a reputable eco-lodge", "Yellow fever vaccination required", "Pack lightweight long-sleeve clothing"],
    estimatedDailyBudget: 5000,
    coordinates: { lat: -3.4653, lng: -62.2159 },
  },
  {
  name: "Phuket",
  country: "Thailand",
  image: "/images/destinations/Phuket.jpg",
  images: [
    "/images/destinations/Phuket.jpg",
  ],
  rating: 4.6, reviewCount: 4800, price: 900, duration: "5 Days", category: "Beach",
  description: "Thailand's largest island offers a perfect blend of crystal-clear beaches, vibrant nightlife, Buddhist temples, and incredible street food.",
  shortDescription: "Beaches, temples and Thai street food",
  bestTimeToVisit: "November to April",
  topAttractions: ["Phi Phi Islands", "Big Buddha", "Patong Beach", "Phang Nga Bay"],
  activities: ["Island hopping", "Snorkeling", "Muay Thai show", "Thai cooking class"],
  foodRecommendations: ["Pad Thai", "Tom yum goong", "Som tam papaya salad", "Mango sticky rice"],
  travelTips: ["Rent a scooter to explore", "Negotiate tuk-tuk prices", "Respect dress codes at temples"],
  estimatedDailyBudget: 3500,
  coordinates: { lat: 7.8804, lng: 98.3923 },
},
  {
  name: "Prague",
  country: "Czech Republic",
  image: "/images/destinations/Prague.jpg",
  images: [
    "/images/destinations/Prague.jpg",
  ],
  rating: 4.7, reviewCount: 3600, price: 1000, duration: "4 Days", category: "Historical",
  description: "One of Europe's most beautiful medieval cities — Prague's fairy-tale architecture, Gothic spires, and vibrant arts scene enchant every visitor.",
  shortDescription: "Fairy-tale medieval city of spires",
  bestTimeToVisit: "May to June, September to October",
  topAttractions: ["Prague Castle", "Charles Bridge", "Old Town Square", "Astronomical Clock"],
  activities: ["Castle tour", "Vltava river cruise", "Beer spa experience", "Jewish Quarter tour"],
  foodRecommendations: ["Svíčková (beef with cream sauce)", "Trdelník", "Goulash with bread dumplings", "Czech pilsner"],
  travelTips: ["Old Town is very walkable", "Trams are the best transport", "Book popular restaurants in advance"],
  estimatedDailyBudget: 3500,
  coordinates: { lat: 50.0755, lng: 14.4378 },
},
 {
  name: "Cape Town",
  country: "South Africa",
  image: "/images/destinations/Cape Town.jpg",
  images: [
    "/images/destinations/Cape Town.jpg",
  ],
  rating: 4.8, reviewCount: 3200, price: 1400, duration: "5 Days", category: "Adventure",
  description: "Dramatic Table Mountain, pristine beaches, world-class wine estates, and incredible wildlife all within reach of this stunning coastal city.",
  shortDescription: "Table Mountain, beaches and Cape winelands",
  bestTimeToVisit: "November to March",
  topAttractions: ["Table Mountain", "Cape of Good Hope", "Boulders Beach Penguins", "V&A Waterfront"],
  activities: ["Table Mountain cable car", "Cape Peninsula drive", "Wine tasting in Stellenbosch", "Shark cage diving"],
  foodRecommendations: ["Braai (BBQ)", "Bobotie", "Bunny chow", "Cape Malay curry"],
  travelTips: ["Car hire is recommended", "Table Mountain often covered in cloud — check forecast", "Load-shedding may affect plans"],
  estimatedDailyBudget: 5000,
  coordinates: { lat: -33.9249, lng: 18.4241 },
},
  {
    name: "Swiss Alps Trekking",
    country: "Switzerland",
    image: "/images/destinations/Swiss Alps Trekking.jpg",
    images: ["/images/destinations/Swiss Alps Trekking.jpg"],
    rating: 4.8, reviewCount: 1800, price: 1600, duration: "4 Days", category: "Adventure",
    description: "High-altitude trails with breathtaking alpine panoramas — from the Matterhorn views at Zermatt to the Bernese Oberland's iconic peaks.",
    shortDescription: "High-altitude alpine trails and panoramas",
    bestTimeToVisit: "June to September",
    topAttractions: ["Matterhorn view from Zermatt", "Jungfrau Region", "Aletsch Glacier", "Eiger Trail"],
    activities: ["Multi-day trekking", "Via ferrata", "Mountain biking", "Alpine hut stays"],
    foodRecommendations: ["Älplermagronen", "Raclette at mountain hut", "Älplerchäs (alpine cheese)"],
    travelTips: ["Trail conditions vary — check forecast", "Half Fare Card saves money on mountain transport", "Book alpine huts in advance in summer"],
    estimatedDailyBudget: 7000,
    coordinates: { lat: 46.0207, lng: 7.7491 },
  },
 {
  name: "Mysore Zoo",
  country: "India", state: "Karnataka",
  image: "/images/destinations/Mysore Zoo.jpg",
  images: [
    "/images/destinations/Mysore Zoo.jpg",
  ],
  rating: 4.3, reviewCount: 3100, price: 100, duration: "1 Day", category: "Nature",
  description: "One of India's oldest and best-maintained zoos, home to white tigers, gorillas, hippos, and hundreds of bird and reptile species.",
  shortDescription: "One of India's oldest and finest zoos",
  bestTimeToVisit: "October to February",
  topAttractions: ["White tiger enclosure", "Reptile house", "Gorilla habitat", "Penguin exhibit"],
  activities: ["Wildlife viewing", "Photography", "Battery car ride", "Children's play area"],
  foodRecommendations: ["Zoo cafeteria snacks", "Mysore pak from outside", "Fresh juice stalls"],
  travelTips: ["Pair with Mysore Palace visit", "Morning visit for active animals", "Toy train ride is popular with kids"],
  estimatedDailyBudget: 600,
  coordinates: { lat: 12.3009, lng: 76.6601 },
},
];

const packages = [
  { name: "Munnar Tea Trail Escape", destination: "Munnar", image: "/images/destinations/Munnar Tea Trail Escape.jpg", duration: "4 Days", price: 950, rating: 4.7, includes: ["Hotel", "Food", "Tea Factory Tour", "Transport"] },
  { name: "Goa Beach & Nightlife Package", destination: "Goa Beaches", image: "/images/destinations/Goa Beach & Nightlife Package.jpg", duration: "4 Days", price: 1100, rating: 4.6, includes: ["Hotel", "Food", "Water Sports", "Transport"] },
  { name: "Ladakh Bike Expedition", destination: "Ladakh", image: "/images/destinations/Ladakh Bike Expedition.jpg", duration: "6 Days", price: 1800, rating: 4.9, includes: ["Hotel", "Food", "Bike Rental", "Permits"] },
  { name: "Bali Adventure Escape", destination: "Bali", image: "/images/destinations/Bali Adventure Escape.jpg", duration: "5 Days", price: 1400, rating: 4.8, includes: ["Hotel", "Food", "Activities", "Transport"] },
  { name: "Romantic Paris Getaway", destination: "Paris", image: "/images/destinations/Romantic Paris Getaway.jpg", duration: "6 Days", price: 2300, rating: 4.9, includes: ["Hotel", "Food", "Eiffel Tour", "Transport"] },
  { name: "Swiss Alps Explorer", destination: "Switzerland", image: "/images/destinations/Swiss Alps Explorer.jpg", duration: "7 Days", price: 2800, rating: 4.9, includes: ["Hotel", "Food", "Cable Car Pass", "Transport"] },
  { name: "Maldives Honeymoon Special", destination: "Maldives", image: "/images/destinations/Maldives Honeymoon Special.jpg", duration: "5 Days", price: 2600, rating: 5.0, includes: ["Water Villa", "Food", "Snorkeling", "Transfer"] },
  { name: "Kerala Backwater Bliss", destination: "Kerala Backwaters, Alappuzha", image: "/images/destinations/Kerala Backwater Bliss.jpg", duration: "3 Days", price: 1100, rating: 4.7, includes: ["Houseboat", "Food", "Ayurveda Spa", "Transport"] },
  { name: "Golden Triangle Heritage Tour", destination: "Taj Mahal, Agra", image: "/images/destinations/Golden Triangle Heritage Tour.jpg", duration: "5 Days", price: 1200, rating: 4.8, includes: ["Hotel", "Food", "Guide", "Transport"] },
  { name: "Tokyo City Explorer", destination: "Tokyo", image: "/images/destinations/Tokyo City Explorer.jpg", duration: "6 Days", price: 2200, rating: 4.9, includes: ["Hotel", "Food", "Rail Pass", "Activities"] },
  { name: "Safari Kenya Adventure", destination: "Safari, Kenya", image: "/images/destinations/Safari Kenya Adventure.jpg", duration: "7 Days", price: 3500, rating: 5.0, includes: ["Lodge", "Food", "Game Drives", "Flights"] },
  { name: "Andaman Dive & Relax", destination: "Andaman Islands", image: "/images/destinations/Andaman Dive & Relax.jpg", duration: "5 Days", price: 1400, rating: 4.8, includes: ["Hotel", "Food", "Scuba", "Ferry"] },
];

const importData = async () => {
  try {
    await Destination.deleteMany();
    await Package.deleteMany();
    await Destination.insertMany(destinations);
    await Package.insertMany(packages);
    console.log(`✅ Data imported successfully! ${destinations.length} destinations, ${packages.length} packages.`);
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};

importData();
